### ISSUE TITLE
Implementing an advanced search (suggesting modifiers, using saved searches)

### ISSUE THREAD

**Issue by agentcross** [lukaspustina/Evernote.lbaction#4]
It would be nice to have advanced search options (e.g. in a dropdown menu) to simplify making use of Evernote's search syntax. 

- make modifiers available in the suggestions (before entering a search query)
- save your favorite searches such that they are accessible from the suggestions as well. 

That is what I adapted to your action to better fit my needs. However, saving specific searches (e.g. all notes of a certain notebook) will require the user to adapt the code.

**Comment by lukaspustina** [comment]
Hi @agentcross. I have a preview regarding saved searches in branch v0.2 that you can check out. It's rough around the edges and lacks icons as well as documentation -- there is a minimalistic roadmap in the Readme#Todo section. I'll appreciate your feedback.

**Comment by agentcross** [comment]
Hi Lukas, I have had sometime now to review your new version. 
First of all, I really like the way of using live suggestions and handling notes as items instead of the suggestions script. 

I like: 
- using the note's ID makes it much more robust (I had troubles open notes which had the same title)
- the way of accessing and editing saved searches is really cool. Using the option "Edit searches" is pretty straightforward and even without documentation easy to use and what I really like about it is that you can use different icons.
- providing more of Evernote's functions (e.g. sync, create note) as options in the 'top level menu' 

Short comings of this version: 

- the biggest issue  (and for me the biggest drawback) with using live feedback that I can see at the moment is the fact that it makes accessing recently edited notes (or notes you use a lot) slower than compared to the old version. Within the old version I just typed a short query (from which I knew that the note I want to open is the most recent) and hit return. There was no need to wait for Evernote to respond to the search but just open the desired note. 
- having a short cut to copy a note's link is nice but not yet as luxury as I would like it to be :-p. Perhaps it would be possible to save the link as formatted text with the title of the note as the visible text and the note's link as link of this text?
- I am missing creating notes from the query by hitting shift+return. I know it's due to the refactoring but perhaps this functionality can be kept by passing the query to the 'handle_note' handler?
- as the action uses chevrons it would be much more intuitively to be used when it would be able to navigate it by using the arrow keys. However, I guess you did implement it like this because it still allows opening Evernote from just running the action. I contacted the customer service to see if there is away of distinguishing between return key and right arrow key for custom actions. The guy told me he will discuss this with one of the developers and will come back to me as soon as he gets an response. 

Further suggestions / ideas of improvement: 
- Hitting cmd+return on a note could open a menu with different options like
    - change notebook
    - edit tags
    - rename
    - copy link 
    - share copy (etc. or whatsoever)
- another thing I recognized when using the action is that I sometimes want to open a couple of notes at a time (lets say I am looking for notes of a notebook and there are a couple that I need to open). For this it would be cool to be able to select several note before opening or to keep the launchbar search active when opening a note holding an action key. Again - this is pure luxury. 

These are all my thoughts on it so far. Probably I will have a look and try to work on few things that I stated on my own. Will let you know if I come up with something worthy of mention. 

Thanks for your work! 
Christian

**Comment by lukaspustina** [comment]
@agentcross Thanks for the review.

Regarding your likes: 
* Note Links: That's exactly the reason. I makes opening notes stable.
* Saved Search: I'm glad you find it helpful. I use it extensively. You should checkout Favorite Notes as well.
* Sync Notes seemed to be obvious because I need to for collaboration with other quite often.

Regarding your dislikes:
* Opening blindly: Yes, that's a direct consequence of using note links. In v0.1 the search you typed was passed to Evernote to open the link. Since you have to select and item now to get the note link, this is not possible anymore. Maybe Favorite Notes helps here.
* Unfortunately, that's not possible at the moment. The problem is that every application decides on its own how to paste an item from the clipboard. So I have little influence on that. But it's still on my list.
* I have no clear picture of how this should work in the current implementation. Please open a new issue and describe the workflow.
* I don't get the chevron comment.

Regarding your further suggestions:
* Additional options: I don't see this coming, because Evernote does not expose the corresponding information via AppleScript like "get tags, get notebooks" etc. These features also seem misplaced in the Launchbar Action which IMO shoudl stay lightweight.
* Opening multiple notes: I see where this is coming from. Launchbar has this feature for files etc. But it's not exposed to Actions. 

@agentcross So thank you very much for helping me to enhance and extend this action. Your comments are highly appreciated! Please ping me, if you have more ideas.

**Comment by lukaspustina** [comment]
Just a minor update: I just implemented a version of "open main window with search query". Maybe you had a similar idea.
